services:
  wordpress:
    image: wordpress:php8.2-apache
    container_name: wp_web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: 10.0.40.204
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        $$table_prefix = 'inmo_';
        define('WP_HOME', 'https://zitadel.a24iriabc.iesteis.gal');
        define('WP_SITEURL', 'https://zitadel.a24iriabc.iesteis.gal');
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - ./wp-data:/var/www/html
      - ./apache2/000-default-ssl.conf:/etc/apache2/sites-available/000-default-ssl.conf
      - ./apache2/certs:/etc/apache2/ssl
